title: My Portfolio
logo: /assets/img/foto_akil_circle2.png
#author:
  #name: Muhammad Sidratul Muntaha Al Mutawakkil Alallah
  #email: m.sidratul.muntaha92@gmail.com
description: "This is Muhammad Sidratul Muntaha Al Mutawakkil Alallah's portfolio."
show_downloads: true
footer: false
theme: jekyll-theme-minimal
