title: Akil's Portfolio
#logo: /assets/img/
author:
  name: Muhammad Sidratul Muntaha Al Mutawakkil Alallah
  email: m.sidratul.muntaha92@gmail.com
description: "Great site about Jekyll on GH-Pages."
show_downlaods: true
theme: jekyll-theme-minimal
